INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR001', 'Kelas');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR002', 'Aula_Indoor');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR003', 'Aula_Outdoor');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR004', 'Lab');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR005', 'Lapangan_Indoor');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR006', 'Lapangan_Outdoor');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR007', 'Fasor');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR008', 'CCWS');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR009', 'Workshop');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR010', 'Hall');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR011', 'Ballroom');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR012', 'Kolam_Renang');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR013', 'Perpustakaan');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR014', 'Studio Musik');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR015', 'Studio Seni');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR016', 'Studio Tari');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR017', 'Perpustakaan');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR018', 'Auditorium');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR019', 'Theater');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR020', 'Taman');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR021', 'Masjid');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR022', 'Parkiran');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR023', 'Musholla');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR024', 'Ruang Sidang');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR025', 'Ruang Penelitian');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR026', 'Ruang Dosen');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR027', 'Ruang Rapat');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR028', 'Ruang Tamu');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR029', 'Kantin');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR030', 'Ruko');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR031', 'Ruang UKM');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR032', 'Gudang');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR033', 'Ruang Riset');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR034', 'Ruang Konseling');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR035', 'Ruang Arsip');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR036', 'Ruang Siaran');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR037', 'Ruang Proyek');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR038', 'Ruang Desain');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR039', 'Ruang Tata Usaha');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR040', 'Ruang Administrasi');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR041', 'Ruang Tutorial');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR042', 'Ruang Kewirauahaan');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR043', 'Ruang UKM');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR044', 'Kelas Pascasarjana');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR045', 'Smartclassroom');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR046', 'Asrama');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR047', 'Apartemen');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR048', 'Sirkuit');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR049', 'Studio Desain');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR050', 'Graha');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR051', 'Ruang Seminar');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR052', 'Ruang Robotik');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR053', 'Ruang Biolab');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR054', 'Ruang Edukasi');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR055', 'Ruang Baca');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR056', 'Ruang Galeri');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR057', 'Ruang Podcast');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR058', 'Galeri');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR059', 'Ruang komunitas');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR060', 'Ruang Pelatihan');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR061', 'Pos');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR062', 'UKS');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR063', 'Ruang Carrer Center');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR064', 'Ruang budaya');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR065', 'Ruang Data');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR066', 'Ruang IT');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR067', 'Ruang Akademik');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR068', 'Ruang Tendik');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR069', 'Ruang Rektorat');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR070', 'Ruang HIMA');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR071', 'Ruang Humas');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR072', 'Ruang Editing');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR073', 'Ruang kostum');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR074', 'Ruang ganti');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR075', 'Ruang orkestra');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR076', 'Ruang VFX');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR077', 'Ruang Design');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR078', 'Ruang UI UX');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR079', 'Ruang Rendering');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR080', 'Ruang automatika');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR081', 'Ruang cinema');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR082', 'Ruang Visual');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR083', 'Ruang audio');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR084', 'Ruang penitipaan barang');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR085', 'Ruang Tata Usaha Fakultas');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR086', 'Ruang Tata Usaha Departemen');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR087', 'Ruang Unit Pelaksana Teknis');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR088', 'Ruang Keuangan');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR089', 'Ruang Dekanat');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR090', 'Ruangan Kerohanian');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR091', 'Ruang BEM');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR092', 'Ruang Multimedia');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR093', 'Ruang Diskusi');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR094', 'Ruang Bahasa');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR095', 'Ruang Praktikum');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR096', 'Ruang Wisma');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR097', 'Ruang Konseling spiritual');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR098', 'Ruang Inklusi');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR099', 'Ruang layanan konsultasi');
INSERT INTO jenis_ruangan (jenis_id, jenis_nama) VALUES ('JR100', 'Ruang IGD');
